language: ruby
cache:
  bundler: true
  yarn: true
before_install:
  - gem update --system 3.0.3
  - gem update bundler
install: bundle install --deployment
env:
  - DOCS_BASE_PATH="." OAS_PATH="_open_api/api_specs/definitions"
before_script:
  - |
    if [ -z "$SSH_KEY_REQUIRED" ]; then
      echo "Skipping setting up SSH Key";
    else
      echo "Setting up SSH key";
      declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
      openssl aes-256-cbc -K $encrypted_293bfe86302a_key -iv $encrypted_293bfe86302a_iv -in "github_deploy_key.enc" -out "$SSH_FILE" -d
      chmod 600 "$SSH_FILE" \
        && printf "%s\n" \
             "Host github.com" \
             "  IdentityFile $SSH_FILE" \
             "  LogLevel ERROR" >> ~/.ssh/config
    fi
script:
  - bundle exec nexmo-developer --docs='.'